version: '3.8'
services:
  frontend:
    image: 'hashicorpdemoapp/frontend:v1.0.9'
    environment:
      - NEXT_PUBLIC_PUBLIC_API_URL=http://public-api:8081
    ports:
      - 3000:3000
  nginx:
    image: hashicorpdemoapp/frontend-nginx:v1.0.9
    links:
      - 'public-api:public-api'
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  public-api:
    image: 'hashicorpdemoapp/public-api:v0.0.7'
    environment:
      - PRODUCT_API_URI=product-api:9090
      - PAYMENT_API_URI=payments:8080
      - BIND_ADDRESS=127.0.0.1:8081
    links:
      - 'product-api:product-api'
      - 'payments:payments'
    ports:
      - '8081:8081'
  product-api:
    image: 'hashicorpdemoapp/product-api:v0.0.22'
    volumes:
      - type: bind
        source: ./conf.json
        target: /conf.json
    links:
      - 'product-db:product-db'
    ports:
      - '9090:9090'
    depends_on:
      - product-db
  product-db:
    image: 'hashicorpdemoapp/product-api-db:v0.0.22'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=products
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
  payments:
    image: 'hashicorpdemoapp/payments:latest'
    ports:
      - '8080:8080'


    